name: test-fuzzer-ci-still-works
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build-duckdb:
    name: Build DuckDB
    uses: duckdblabs/duckdb-fuzzer-ci/.github/workflows/build_fuzzer.yml@main
    with:
      git_url: ${{ github.actor }}
      git_tag: ${{ github.ref_name }}
      timeout-minutes: 120

  fuzzer:
    name: Fuzzer
    needs:
    - build-duckdb
    strategy:
      fail-fast: false
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [emptyalltypes]
    uses: duckdblabs/duckdb-fuzzer-ci/.github/workflows/fuzz_duckdb.yml@main
    with:
      fuzzer: ${{ matrix.fuzzer }}
      data: ${{ matrix.data }}
      timeout-minutes: 20
      max_queries: 10
      dry: false