name: test-fuzzer-ci-still-works
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build-duckdb:
    name: Build DuckDB
    # should be a valid tag, branch name or commit. After it gets merged, we can replace it with the branch name
    uses: duckdblabs/duckdb-fuzzer-ci/.github/workflows/reusable_build.yml@a718b91bfe729290ad0525722cd77651416d2046
    with:
      git_url: ${{ github.actor }}
      git_tag: ${{ github.ref_name }}
      timeout-minutes: 120

  fuzzer:
    name: Fuzzer
    needs:
    - build-duckdb
    strategy:
      fail-fast: false
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [emptyalltypes]
    uses: duckdblabs/duckdb-fuzzer-ci/.github/workflows/reusable_fuzzer.yml@a718b91bfe729290ad0525722cd77651416d2046
    with:
      fuzzer: ${{ matrix.fuzzer }}
      data: ${{ matrix.data }}
      timeout-minutes: 20
      max_queries: 10